---
- name: Create spark folder
  tags: 'spark'
  become: yes
  file:
    path: "{{ spark_directory }}"
    owner: ubuntu
    group: ubuntu
    recurse: yes
    state: directory

- name: Configure spark docker-compose
  tags: 'spark'
  become: yes
  template:
    src: spark-cluster-docker-compose.yaml.j2
    dest: "{{ spark_directory }}/docker-compose.yaml"
    owner: ubuntu
    group: ubuntu

- name: Run docker Compose
  tags: 'spark'
  become: yes
  docker_compose:
    project_src: "{{ spark_directory }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always