# COMP90024 Cluster and Cloud Computer Team 12
# @Author: Shizhe Cai
# @student id: 798125
# @email: shizhec@student.unimelb.edu.au
---
# create working directory for spark
- name: Create spark folder
  tags: 'spark'
  become: yes
  file:
    path: "{{ spark_directory }}"
    owner: ubuntu
    group: ubuntu
    recurse: yes
    state: directory

# configure docker-compose file for spark
- name: Configure spark docker-compose
  tags: 'spark'
  become: yes
  template:
    src: spark-cluster-docker-compose.yaml.j2
    dest: "{{ spark_directory }}/docker-compose.yaml"
    owner: ubuntu
    group: ubuntu

# run spark docker compose
- name: Run docker Compose
  tags: 'spark'
  become: yes
  docker_compose:
    project_src: "{{ spark_directory }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always