# COMP90024 Cluster and Cloud Computer Team 12
# @Author: Shizhe Cai
# @student id: 798125
# @email: shizhec@student.unimelb.edu.au

---
# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk