# COMP90024 Cluster and Cloud Computer Team 12
# @Author: Shizhe Cai
# @student id: 798125
# @email: shizhec@student.unimelb.edu.au
---
- name: Uninstall old versions of docker
  tags: 'install-docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Add Docker apt repository key
  tags: 'install-docker'
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  tags: 'install-docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'install-docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'install-docker'
  become: yes
  pip:
    name: ['docker-compose']
    state: latest


# configure docker proxy service
- name: Create directory
  tags: 'docker'
  become: yes
  file:
    path: "{{ docker_service_directory }}"
    recurse: yes
    state: directory

- name: create docker proxy file
  tags: 'docker'
  become: yes
  copy:
    content: "[Service]\n"
    dest: "{{ docker_service_directory }}/{{ docer_proxy_configure_file }}"

- name: add proxy to docker service
  become: yes
  lineinfile:
    line: "Environment=\"HTTP_PROXY={{ http_proxy }}\"\nEnvironment=\"HTTPS_PROXY={{ http_proxy }}\"\nEnvironment=\"NO_PROXY=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au\"\n"
    dest: "{{ docker_service_directory }}/{{ docer_proxy_configure_file }}"

- name: reload daemond
  become: yes
  command: systemctl daemon-reload

- name: restart docker
  become: yes
  command: systemctl restart docker

- name: fix connect to the Docker daemon socket
  become: yes
  command: chmod 666 /var/run/docker.sock
