---
- name: Create couchdb directory
  tags: 'couchdb'
  become: yes
  file:
    path: "{{ couchdb_directory }}"
    owner: "{{ ansible_user }} "
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure docker compose for couchdb
  tags: 'couchdb'
  become: yes
  template:
    src: docker-compose-couchdb.yaml.j2
    dest: "{{ couchdb_directory}}/docker-compose-couchdb.yaml.j2"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: "couchdb"
  become: yes
  docker_service:
    project_src: "{{ couchdb_directory }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always