# COMP90024 Cluster and Cloud Computer Team 12
# @Author: Shizhe Cai
# @student id: 798125
# @email: shizhec@student.unimelb.edu.au
---
- hosts: couchdb
  remote_user: ubuntu
  vars_files:
    - host_vars/application_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb-cluster

- hosts: localhost
  vars_files:
    - host_vars/application_vars.yaml
  shell: setup-couchdb-cluster.sh
  args:
    chdir: "{{ local }}/"

- hosts: instance1
  remote_user: ubuntu
  vars_files:
    - host_vars/application_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-web-server

- hosts: instance2
  remote_user: ubuntu
  vars_files:
    - host_vars/application_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-spark


- hosts: instance3
  remote_user: ubuntu
  vars_files:
    - host_vars/application_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-daily-scraper