---
# - hosts: couchdb
#   remote_user: ubuntu
#   vars_files:
#     - host_vars/application_vars.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-couchdb-cluster

- hosts: instance1
  remote_user: ubuntu
  vars_files:
    - host_vars/application_vars.yaml
  gather_facts: true
  roles:
    - role: deploy-web-server

# - hosts: instance2
#   remote_user: ubuntu
#   vars_files:
#     - host_vars/application_vars.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-spark