# COMP90024 Cluster and Cloud Computer Team 12
# @Author: Shizhe Cai
# @student id: 798125
# @email: shizhec@student.unimelb.edu.au
---
- hosts: all
  vars_files:
    - host_vars/nectar_vars.yaml
  gather_facts: true
  roles:
    - role: install-environments
    - role: mount-volumes
