# COMP90024 Cluster and Cloud Computer Team 12
# @Author: Shizhe Cai
# @student id: 798125
# @email: shizhec@student.unimelb.edu.au
- hosts: localhost
  vars_files:
    - host_vars/nectar_vars.yaml
  gather_facts: true

  roles:
    - role: common
    - role: list-images
    - role: create-volume
    - role: create-security-group
    - role: create-instance